"""
Seed data for Scrolic (Users, Strategies, Posts, Comments, Notifications)
Production-ready: Removed mock cTrader accounts so real user cTrader accounts are populated upon connecting.
"""
from datetime import datetime, timezone

SEED_STRATEGIES = [
    {
        "id": "breakout",
        "name": "Breakout Hunter",
        "slug": "breakout-hunter",
        "description": "Menangkap ekspansi volatilitas dan momentum saat harga menembus level supply/demand kunci.",
        "template_id": "breakout",
        "tagline": "High Probability Momentum",
        "win_rate_avg": 78.5,
        "premium": False,
        "active": True,
        "accentColor": "#F59E0B",
        "accentBg": "bg-amber-500/10",
        "accentBorder": "border-amber-500/30",
        "badgeClass": "bg-amber-500/20 text-amber-400 border-amber-500/30",
        "gradient": "from-amber-500 to-orange-600",
        "positionBarGradient": "from-amber-500 via-orange-500 to-amber-400",
        "fontVibe": "font-mono tracking-tight",
        "icon": "Zap",
        "popularPairs": ["XAUUSD", "BTCUSD", "GBPUSD"],
        "riskStyle": "Aggressive Momentum",
        "created_at": datetime(2026, 1, 1, 0, 0, 0, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 1, 1, 0, 0, 0, tzinfo=timezone.utc)
    },
    {
        "id": "scalping",
        "name": "Precision Scalper",
        "slug": "precision-scalper",
        "description": "Eksekusi mikro-struktur orderflow dengan Risk-to-Reward terukur pada timeframe 1M-5M.",
        "template_id": "scalping",
        "tagline": "High Frequency Flow",
        "win_rate_avg": 81.2,
        "premium": False,
        "active": True,
        "accentColor": "#10B981",
        "accentBg": "bg-emerald-500/10",
        "accentBorder": "border-emerald-500/30",
        "badgeClass": "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
        "gradient": "from-emerald-500 to-teal-600",
        "positionBarGradient": "from-emerald-500 via-teal-500 to-emerald-400",
        "fontVibe": "font-sans font-bold",
        "icon": "Activity",
        "popularPairs": ["EURUSD", "GBPUSD", "USDJPY"],
        "riskStyle": "Tight Stop Loss",
        "created_at": datetime(2026, 1, 1, 0, 0, 0, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 1, 1, 0, 0, 0, tzinfo=timezone.utc)
    },
    {
        "id": "smc",
        "name": "Smart Money Concept (SMC)",
        "slug": "smart-money-concept",
        "description": "Trading searah akumulasi dan distribusi institusi melalui Order Block, FVG, dan Liquidity Sweep.",
        "template_id": "smc",
        "tagline": "Institutional Liquidity",
        "win_rate_avg": 84.0,
        "premium": True,
        "active": True,
        "accentColor": "#8B5CF6",
        "accentBg": "bg-purple-500/10",
        "accentBorder": "border-purple-500/30",
        "badgeClass": "bg-purple-500/20 text-purple-400 border-purple-500/30",
        "gradient": "from-purple-500 to-indigo-600",
        "positionBarGradient": "from-purple-500 via-indigo-500 to-purple-400",
        "fontVibe": "font-serif italic",
        "icon": "TrendingUp",
        "popularPairs": ["EURUSD", "XAUUSD", "GBPUSD"],
        "riskStyle": "High R:R Ratio",
        "created_at": datetime(2026, 1, 1, 0, 0, 0, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 1, 1, 0, 0, 0, tzinfo=timezone.utc)
    },
    {
        "id": "swing",
        "name": "Macro Swing Master",
        "slug": "macro-swing-master",
        "description": "Mengikuti gelombang trend fundamental dan kebijakan bank sentral untuk horizon multi-hari.",
        "template_id": "swing",
        "tagline": "Multi-Day Trend Riding",
        "win_rate_avg": 76.8,
        "premium": False,
        "active": True,
        "accentColor": "#3B82F6",
        "accentBg": "bg-blue-500/10",
        "accentBorder": "border-blue-500/30",
        "badgeClass": "bg-blue-500/20 text-blue-400 border-blue-500/30",
        "gradient": "from-blue-500 to-cyan-600",
        "positionBarGradient": "from-blue-500 via-cyan-500 to-blue-400",
        "fontVibe": "font-sans uppercase tracking-widest",
        "icon": "Globe",
        "popularPairs": ["GBPUSD", "AUDUSD", "EURJPY"],
        "riskStyle": "Wide Horizon Swing",
        "created_at": datetime(2026, 1, 1, 0, 0, 0, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 1, 1, 0, 0, 0, tzinfo=timezone.utc)
    }
]

SEED_USERS = [
    {
        "id": "user-alex",
        "username": "alex_trader",
        "display_name": "Alex Sterling",
        "email": "alex.sterling@scrolic.com",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
        "bio": "Professional Momentum & Breakout Trader. Trading Gold (XAUUSD) & Major FX with strict Risk-Reward.",
        "role": "admin",
        "premium": True,
        "subscription_tier": "premium_yearly",
        "energy": 0,
        "followers_count": 1420,
        "following_count": 38,
        "trades_count": 428,
        "win_rate": 81.4,
        "is_verified": True,
        "strategy_dna": "breakout",
        "primary_strategy_id": "breakout",
        "following_list": ["sarah_scalper", "ray_swing"],
        "saved_post_ids": [],
        "referral_code": "SCROLIC50",
        "referrals_count": 48,
        "affiliate_earnings_energy": 0,
        "trade_earnings_energy": 0,
        "ctrader_account_id": "cTrader-47601047",
        "ctrader_accounts": [
            {
                "accountId": "cTrader-47601047",
                "accountNo": "47601047",
                "brokerName": "FPMarkets STL",
                "accountType": "LIVE",
                "currency": "USD",
                "balance": 664.31,
                "leverage": 30,
                "isLive": True
            },
            {
                "accountId": "cTrader-47902963",
                "accountNo": "47902963",
                "brokerName": "Raw Trading Ltd",
                "accountType": "LIVE",
                "currency": "USD",
                "balance": 706.67,
                "leverage": 1000,
                "isLive": True
            },
            {
                "accountId": "cTrader-47905692",
                "accountNo": "47905692",
                "brokerName": "Spotware cTrader ECN",
                "accountType": "LIVE",
                "currency": "USD",
                "balance": 1000.0,
                "leverage": 500,
                "isLive": True
            }
        ],
        "ctrader_connected": True,
        "default_unlock_price": 1,
        "default_follow_price": 1,
        "created_at": datetime(2026, 1, 10, 10, 0, 0, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 8, 20, 10, 0, 0, tzinfo=timezone.utc)
    },
    {
        "id": "user-sarah",
        "username": "sarah_scalper",
        "display_name": "Sarah Lin, CMT",
        "email": "sarah.lin@scrolic.com",
        "avatar": "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80",
        "bio": "Chartered Market Technician. High-frequency scalper on EURUSD & GBPUSD 1m-5m orderflow.",
        "role": "user",
        "premium": True,
        "subscription_tier": "premium_monthly",
        "energy": 0,
        "followers_count": 2890,
        "following_count": 14,
        "trades_count": 934,
        "win_rate": 77.8,
        "is_verified": True,
        "strategy_dna": "scalping",
        "primary_strategy_id": "scalping",
        "following_list": ["alex_trader"],
        "saved_post_ids": [],
        "referral_code": "SARAHFX",
        "referrals_count": 32,
        "affiliate_earnings_energy": 0,
        "trade_earnings_energy": 0,
        "ctrader_account_id": None,
        "ctrader_accounts": [],
        "ctrader_connected": False,
        "default_unlock_price": 1,
        "default_follow_price": 1,
        "created_at": datetime(2026, 2, 15, 12, 0, 0, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 8, 20, 10, 0, 0, tzinfo=timezone.utc)
    },
    {
        "id": "user-elena",
        "username": "elena_smc",
        "display_name": "Elena Rostova",
        "email": "elena.rostova@scrolic.com",
        "avatar": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80",
        "bio": "Institutional SMC Trader. Catching liquidity runs and multi-timeframe change of character.",
        "role": "user",
        "premium": True,
        "subscription_tier": "premium_6m",
        "energy": 0,
        "followers_count": 3410,
        "following_count": 22,
        "trades_count": 312,
        "win_rate": 83.2,
        "is_verified": True,
        "strategy_dna": "smc",
        "primary_strategy_id": "smc",
        "following_list": ["alex_trader", "sarah_scalper"],
        "saved_post_ids": [],
        "referral_code": "ELENASMC",
        "referrals_count": 67,
        "affiliate_earnings_energy": 0,
        "trade_earnings_energy": 0,
        "ctrader_account_id": None,
        "ctrader_accounts": [],
        "ctrader_connected": False,
        "default_unlock_price": 1,
        "default_follow_price": 1,
        "created_at": datetime(2026, 3, 1, 8, 0, 0, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 8, 20, 10, 0, 0, tzinfo=timezone.utc)
    },
    {
        "id": "user-ray",
        "username": "ray_swing",
        "display_name": "Raymond Vance",
        "email": "raymond.vance@scrolic.com",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
        "bio": "Macro Swing Trader. Focusing on GBP & JPY pairs with central bank policy alignment.",
        "role": "user",
        "premium": False,
        "subscription_tier": "free",
        "energy": 0,
        "followers_count": 880,
        "following_count": 19,
        "trades_count": 154,
        "win_rate": 74.0,
        "is_verified": True,
        "strategy_dna": "swing",
        "primary_strategy_id": "swing",
        "following_list": ["alex_trader"],
        "saved_post_ids": [],
        "referral_code": "RAYSWING",
        "referrals_count": 11,
        "affiliate_earnings_energy": 90,
        "trade_earnings_energy": 80,
        "ctrader_account_id": None,
        "ctrader_accounts": [],
        "ctrader_connected": False,
        "default_unlock_price": 1,
        "default_follow_price": 1,
        "created_at": datetime(2026, 4, 12, 14, 0, 0, tzinfo=timezone.utc),
        "updated_at": datetime(2026, 8, 20, 10, 0, 0, tzinfo=timezone.utc)
    }
]

SEED_POSTS = [
    {
        "id": "post-ctrader-cTrader-47601047-op1",
        "user_id": "user-alex",
        "username": "alex_trader",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
        "trade_id": "trade-cTrader-47601047-op1",
        "symbol": "XAUUSD",
        "market": "Commodity",
        "strategy_id": "breakout",
        "position_type": "BUY",
        "status": "OPEN",
        "entry_price": 2915.90,
        "current_price": 2914.50,
        "progress": 42,
        "profit": -1.40,
        "profit_percent": -0.14,
        "lot": 0.01,
        "pips": -14.0,
        "duration": "Live OP",
        "opened_at": datetime(2026, 8, 26, 6, 0, 0, tzinfo=timezone.utc),
        "visibility": "LOCKED",
        "unlock_price": 1,
        "follow_price": 1,
        "auto_description": "⚡ Posisi Terbuka (OP) cTrader (cTrader-47601047): BUY 0.01 Lot XAUUSD @ 2915.90 (Floating Loss -$1.40)",
        "custom_description": "Posisi Live Terhubung dari akun cTrader cTrader-47601047",
        "likes_count": 12,
        "comments_count": 3,
        "followers_count": 4,
        "liked_by_user_ids": [],
        "followed_by_user_ids": [],
        "unlocked_by_user_ids": []
    },
    {
        "id": "post-ctrader-cTrader-47601047-op2",
        "user_id": "user-alex",
        "username": "alex_trader",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
        "trade_id": "trade-cTrader-47601047-op2",
        "symbol": "BTCUSD",
        "market": "Crypto",
        "strategy_id": "breakout",
        "position_type": "BUY",
        "status": "OPEN",
        "entry_price": 66565.0,
        "current_price": 66500.0,
        "progress": 44,
        "profit": -0.65,
        "profit_percent": -0.07,
        "lot": 0.01,
        "pips": -65.0,
        "duration": "Live OP",
        "opened_at": datetime(2026, 8, 26, 6, 15, 0, tzinfo=timezone.utc),
        "visibility": "LOCKED",
        "unlock_price": 1,
        "follow_price": 1,
        "auto_description": "⚡ Posisi Terbuka (OP) cTrader (cTrader-47601047): BUY 0.01 Lot BTCUSD @ 66565.0 (Floating Loss -$0.65)",
        "custom_description": "Posisi Live Terhubung dari akun cTrader cTrader-47601047",
        "likes_count": 8,
        "comments_count": 1,
        "followers_count": 2,
        "liked_by_user_ids": [],
        "followed_by_user_ids": [],
        "unlocked_by_user_ids": []
    },
    {
        "id": "post-ctrader-cTrader-47601047-hist1",
        "user_id": "user-alex",
        "username": "alex_trader",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
        "trade_id": "trade-cTrader-47601047-hist1",
        "symbol": "BTCUSD",
        "market": "Crypto",
        "strategy_id": "breakout",
        "position_type": "BUY",
        "status": "CLOSED",
        "entry_price": 66500.0,
        "current_price": 68350.0,
        "profit": 1850.00,
        "profit_percent": 18.5,
        "lot": 1.0,
        "pips": 185.0,
        "duration": "4h 12m",
        "opened_at": datetime(2026, 8, 25, 12, 0, 0, tzinfo=timezone.utc),
        "closed_at": datetime(2026, 8, 25, 16, 12, 0, tzinfo=timezone.utc),
        "visibility": "LOCKED",
        "unlock_price": 1,
        "follow_price": 1,
        "auto_description": "Closed Deal via cTrader (cTrader-47601047): BUY 1.00 Lot BTCUSD +$1,850.00",
        "custom_description": "Transaksi cTrader cTrader-47601047 Selesai (Profit)",
        "likes_count": 24,
        "comments_count": 5,
        "followers_count": 8,
        "liked_by_user_ids": [],
        "followed_by_user_ids": [],
        "unlocked_by_user_ids": []
    },
    {
        "id": "post-ctrader-cTrader-47601047-hist2",
        "user_id": "user-alex",
        "username": "alex_trader",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
        "trade_id": "trade-cTrader-47601047-hist2",
        "symbol": "GBPUSD",
        "market": "Forex",
        "strategy_id": "breakout",
        "position_type": "SELL",
        "status": "CLOSED",
        "entry_price": 1.29500,
        "current_price": 1.29080,
        "profit": 420.00,
        "profit_percent": 4.2,
        "lot": 0.3,
        "pips": 42.0,
        "duration": "1h 45m",
        "opened_at": datetime(2026, 8, 25, 10, 0, 0, tzinfo=timezone.utc),
        "closed_at": datetime(2026, 8, 25, 11, 45, 0, tzinfo=timezone.utc),
        "visibility": "LOCKED",
        "unlock_price": 1,
        "follow_price": 1,
        "auto_description": "Closed Deal via cTrader (cTrader-47601047): SELL 0.30 Lot GBPUSD +$420.00",
        "custom_description": "Transaksi cTrader cTrader-47601047 Selesai (Profit)",
        "likes_count": 15,
        "comments_count": 2,
        "followers_count": 3,
        "liked_by_user_ids": [],
        "followed_by_user_ids": [],
        "unlocked_by_user_ids": []
    },
    {
        "id": "post-ctrader-cTrader-47601047-hist3",
        "user_id": "user-alex",
        "username": "alex_trader",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
        "trade_id": "trade-cTrader-47601047-hist3",
        "symbol": "XAUUSD",
        "market": "Commodity",
        "strategy_id": "breakout",
        "position_type": "BUY",
        "status": "CLOSED",
        "entry_price": 2900.00,
        "current_price": 2895.80,
        "profit": -210.00,
        "profit_percent": -2.1,
        "lot": 0.5,
        "pips": -42.0,
        "duration": "25m",
        "opened_at": datetime(2026, 8, 24, 15, 0, 0, tzinfo=timezone.utc),
        "closed_at": datetime(2026, 8, 24, 15, 25, 0, tzinfo=timezone.utc),
        "visibility": "LOCKED",
        "unlock_price": 1,
        "follow_price": 1,
        "auto_description": "Closed Deal via cTrader (cTrader-47601047): BUY 0.50 Lot XAUUSD -$210.00",
        "custom_description": "Transaksi cTrader cTrader-47601047 Selesai (SL Hit)",
        "likes_count": 5,
        "comments_count": 0,
        "followers_count": 1,
        "liked_by_user_ids": [],
        "followed_by_user_ids": [],
        "unlocked_by_user_ids": []
    },
    {
        "id": "post-ctrader-cTrader-47601047-hist4",
        "user_id": "user-alex",
        "username": "alex_trader",
        "avatar": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
        "trade_id": "trade-cTrader-47601047-hist4",
        "symbol": "EURUSD",
        "market": "Forex",
        "strategy_id": "breakout",
        "position_type": "BUY",
        "status": "CLOSED",
        "entry_price": 1.07800,
        "current_price": 1.08480,
        "profit": 680.00,
        "profit_percent": 6.8,
        "lot": 1.0,
        "pips": 68.0,
        "duration": "3h 10m",
        "opened_at": datetime(2026, 8, 24, 9, 0, 0, tzinfo=timezone.utc),
        "closed_at": datetime(2026, 8, 24, 12, 10, 0, tzinfo=timezone.utc),
        "visibility": "LOCKED",
        "unlock_price": 1,
        "follow_price": 1,
        "auto_description": "Closed Deal via cTrader (cTrader-47601047): BUY 1.00 Lot EURUSD +$680.00",
        "custom_description": "Transaksi cTrader cTrader-47601047 Selesai (Profit)",
        "likes_count": 19,
        "comments_count": 4,
        "followers_count": 5,
        "liked_by_user_ids": [],
        "followed_by_user_ids": [],
        "unlocked_by_user_ids": []
    }
]

SEED_COMMENTS = []

SEED_NOTIFICATIONS = [
    {
        "id": "notif-1",
        "user_id": "user-alex",
        "title": "Trade Baru Di-Follow!",
        "message": "Trader @budi_investor telah meniru posisi XAUUSD Anda via 1-Click Mirroring.",
        "type": "FOLLOW",
        "is_read": False,
        "created_at": datetime.now(timezone.utc)
    },
    {
        "id": "notif-2",
        "user_id": "user-alex",
        "title": "Komisi Afiliasi Gen-1 Masuk!",
        "message": "Anda menerima +25 ENERGY (Rp 25.000) dari top-up referral @sarah_scalper.",
        "type": "AFFILIATE_COMMISSION",
        "is_read": False,
        "created_at": datetime.now(timezone.utc)
    }
]
