import { ObjectId } from 'mongodb';
import { MongoUser, MongoPost, MongoStrategy, MongoComment, MongoNotification } from '../models/types';

export const SEED_STRATEGIES: MongoStrategy[] = [
  {
    _id: new ObjectId(),
    id: 'breakout',
    name: 'Breakout Hunter',
    slug: 'breakout-hunter',
    description: 'Menangkap ekspansi volatilitas dan momentum saat harga menembus level supply/demand kunci.',
    template_id: 'breakout',
    tagline: 'High Probability Momentum',
    win_rate_avg: 78.5,
    premium: false,
    active: true,
    created_at: new Date('2026-01-01T00:00:00Z'),
    updated_at: new Date('2026-01-01T00:00:00Z')
  },
  {
    _id: new ObjectId(),
    id: 'scalping',
    name: 'Precision Scalper',
    slug: 'precision-scalper',
    description: 'Eksekusi mikro-struktur orderflow dengan Risk-to-Reward terukur pada timeframe 1M-5M.',
    template_id: 'scalping',
    tagline: 'High Frequency Flow',
    win_rate_avg: 81.2,
    premium: false,
    active: true,
    created_at: new Date('2026-01-01T00:00:00Z'),
    updated_at: new Date('2026-01-01T00:00:00Z')
  },
  {
    _id: new ObjectId(),
    id: 'smc',
    name: 'Smart Money Concept (SMC)',
    slug: 'smart-money-concept',
    description: 'Trading searah akumulasi dan distribusi institusi melalui Order Block, FVG, dan Liquidity Sweep.',
    template_id: 'smc',
    tagline: 'Institutional Liquidity',
    win_rate_avg: 84.0,
    premium: true,
    active: true,
    created_at: new Date('2026-01-01T00:00:00Z'),
    updated_at: new Date('2026-01-01T00:00:00Z')
  },
  {
    _id: new ObjectId(),
    id: 'swing',
    name: 'Macro Swing Master',
    slug: 'macro-swing-master',
    description: 'Mengikuti gelombang trend fundamental dan kebijakan bank sentral untuk horizon multi-hari.',
    template_id: 'swing',
    tagline: 'Multi-Day Trend Riding',
    win_rate_avg: 76.8,
    premium: false,
    active: true,
    created_at: new Date('2026-01-01T00:00:00Z'),
    updated_at: new Date('2026-01-01T00:00:00Z')
  }
];

export const SEED_USERS: MongoUser[] = [
  {
    _id: new ObjectId('650000000000000000000001'),
    id: 'user-alex',
    username: 'alex_trader',
    display_name: 'Alex Sterling',
    email: 'alex.sterling@scrolic.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    bio: 'Professional Momentum & Breakout Trader. Trading Gold (XAUUSD) & Major FX with strict Risk-Reward.',
    role: 'admin',
    premium: true,
    subscription_tier: 'premium_yearly',
    energy: 120,
    followers_count: 1420,
    following_count: 38,
    trades_count: 428,
    win_rate: 81.4,
    is_verified: true,
    strategy_dna: 'breakout',
    primary_strategy_id: 'breakout',
    following_list: ['sarah_scalper', 'ray_swing'],
    saved_post_ids: [],
    referral_code: 'SCROLIC50',
    referrals_count: 48,
    affiliate_earnings_energy: 640,
    ctrader_account_id: 'cTrader-881290',
    ctrader_accounts: [
      { accountId: 'cTrader-881290', brokerName: 'FP Markets', accountType: 'LIVE', currency: 'USD', balance: 25480, leverage: 500, isLive: true },
      { accountId: 'cTrader-339102', brokerName: 'FP Markets', accountType: 'DEMO', currency: 'USD', balance: 50000, leverage: 200, isLive: false },
      { accountId: 'cTrader-190442', brokerName: 'Spotware Open API', accountType: 'DEMO', currency: 'USD', balance: 10000, leverage: 100, isLive: false }
    ],
    ctrader_connected: true,
    created_at: new Date('2026-01-10T10:00:00Z'),
    updated_at: new Date('2026-08-20T10:00:00Z')
  },
  {
    _id: new ObjectId('650000000000000000000002'),
    id: 'user-sarah',
    username: 'sarah_scalper',
    display_name: 'Sarah Lin, CMT',
    email: 'sarah.lin@scrolic.com',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
    bio: 'Chartered Market Technician. High-frequency scalper on EURUSD & GBPUSD 1m-5m orderflow.',
    role: 'user',
    premium: true,
    subscription_tier: 'premium_monthly',
    energy: 85,
    followers_count: 2890,
    following_count: 14,
    trades_count: 934,
    win_rate: 77.8,
    is_verified: true,
    strategy_dna: 'scalping',
    primary_strategy_id: 'scalping',
    following_list: ['alex_trader'],
    saved_post_ids: [],
    referral_code: 'SARAHFX',
    referrals_count: 32,
    affiliate_earnings_energy: 310,
    ctrader_account_id: 'cTrader-449120',
    ctrader_connected: true,
    created_at: new Date('2026-02-15T12:00:00Z'),
    updated_at: new Date('2026-08-20T10:00:00Z')
  },
  {
    _id: new ObjectId('650000000000000000000003'),
    id: 'user-elena',
    username: 'elena_smc',
    display_name: 'Elena Rostova',
    email: 'elena.rostova@scrolic.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    bio: 'Institutional SMC Trader. Catching liquidity runs and multi-timeframe change of character.',
    premium: true,
    subscription_tier: 'premium_6m',
    energy: 240,
    followers_count: 3410,
    following_count: 22,
    trades_count: 312,
    win_rate: 83.2,
    is_verified: true,
    strategy_dna: 'smc',
    primary_strategy_id: 'smc',
    following_list: ['alex_trader', 'sarah_scalper'],
    saved_post_ids: [],
    referral_code: 'ELENASMC',
    referrals_count: 67,
    affiliate_earnings_energy: 890,
    ctrader_account_id: 'cTrader-552190',
    ctrader_connected: true,
    created_at: new Date('2026-03-01T08:00:00Z'),
    updated_at: new Date('2026-08-20T10:00:00Z')
  },
  {
    _id: new ObjectId('650000000000000000000004'),
    id: 'user-ray',
    username: 'ray_swing',
    display_name: 'Ray Pratama',
    email: 'ray.pratama@scrolic.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    bio: 'Macro & Fundamental Swing Trader. Riding high timeframe cycles with patience and calm execution.',
    premium: false,
    subscription_tier: 'free',
    energy: 45,
    followers_count: 880,
    following_count: 19,
    trades_count: 154,
    win_rate: 74.0,
    is_verified: true,
    strategy_dna: 'swing',
    primary_strategy_id: 'swing',
    following_list: ['alex_trader'],
    saved_post_ids: [],
    referral_code: 'RAYSWING',
    referrals_count: 11,
    affiliate_earnings_energy: 90,
    ctrader_account_id: 'cTrader-771829',
    ctrader_connected: true,
    created_at: new Date('2026-04-12T14:00:00Z'),
    updated_at: new Date('2026-08-20T10:00:00Z')
  }
];

export const SEED_POSTS: MongoPost[] = [
  {
    _id: new ObjectId('650000000000000000000101'),
    id: 'post-101',
    user_id: 'user-alex',
    username: 'alex_trader',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    trade_id: 'trade-101',
    symbol: 'XAUUSD',
    market: 'Commodity',
    strategy_id: 'breakout',
    strategy_name: 'BREAKOUT HUNTER',
    position_type: 'BUY',
    status: 'OPEN',
    entry_price: 2914.50,
    current_price: 2928.80,
    progress: 72,
    profit: 2145.00,
    profit_percent: 7.36,
    lot: 1.50,
    stop_loss: 2904.00,
    take_profit: 2938.00,
    pips: 143.0,
    duration: 'Live (42m)',
    opened_at: new Date(Date.now() - 42 * 60000),
    closed_at: null,
    visibility: 'LOCKED',
    unlock_price: 1,
    auto_description: 'Terbuka otomatis via cTrader Open API: BUY 1.50 Lot XAUUSD di level 2914.50.',
    custom_description: 'Breakout H4 Golden Pocket! Mengantisipasi reli lanjutan menuju 2938. Stop Loss ketat di bawah low sesi New York.',
    likes_count: 84,
    comments_count: 12,
    liked_by_user_ids: ['user-sarah'],
    created_at: new Date(Date.now() - 40 * 60000),
    updated_at: new Date(Date.now() - 40 * 60000)
  },
  {
    _id: new ObjectId('650000000000000000000102'),
    id: 'post-102',
    user_id: 'user-sarah',
    username: 'sarah_scalper',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
    trade_id: 'trade-102',
    symbol: 'EURUSD',
    market: 'Forex',
    strategy_id: 'scalping',
    strategy_name: 'PRECISION SCALPER',
    position_type: 'SELL',
    status: 'OPEN',
    entry_price: 1.08420,
    current_price: 1.08210,
    progress: 68,
    profit: 630.00,
    profit_percent: 5.81,
    lot: 3.00,
    stop_loss: 1.08580,
    take_profit: 1.08120,
    pips: 21.0,
    duration: 'Live (18m)',
    opened_at: new Date(Date.now() - 18 * 60000),
    closed_at: null,
    visibility: 'LOCKED',
    unlock_price: 1,
    auto_description: 'Terbuka otomatis via cTrader Open API: SELL 3.00 Lot EURUSD di level 1.08420.',
    custom_description: 'London High fakeout & rejection di VWAP upper band. Quick scalp setup dengan RR 1:3.',
    likes_count: 142,
    comments_count: 26,
    liked_by_user_ids: ['user-alex', 'user-elena'],
    created_at: new Date(Date.now() - 17 * 60000),
    updated_at: new Date(Date.now() - 17 * 60000)
  },
  {
    _id: new ObjectId('650000000000000000000103'),
    id: 'post-103',
    user_id: 'user-elena',
    username: 'elena_smc',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    trade_id: 'trade-103',
    symbol: 'BTCUSD',
    market: 'Crypto',
    strategy_id: 'smc',
    strategy_name: 'SMC INSTITUTIONAL',
    position_type: 'BUY',
    status: 'OPEN',
    entry_price: 68450.00,
    current_price: 69820.00,
    progress: 54,
    profit: 685.00,
    profit_percent: 2.00,
    lot: 0.50,
    stop_loss: 67200.00,
    take_profit: 71500.00,
    pips: 1370.0,
    duration: 'Live (1j 50m)',
    opened_at: new Date(Date.now() - 110 * 60000),
    closed_at: null,
    visibility: 'LOCKED',
    unlock_price: 1,
    auto_description: 'Terbuka otomatis via cTrader Open API: BUY 0.50 Lot BTCUSD di level 68450.00.',
    custom_description: 'SMC Setup: Asian low liquidity swept -> Change of Character (CHoCH) pada timeframe 15m. Target liquidity pool 71.5k.',
    likes_count: 219,
    comments_count: 45,
    liked_by_user_ids: ['user-alex'],
    created_at: new Date(Date.now() - 108 * 60000),
    updated_at: new Date(Date.now() - 108 * 60000)
  },
  {
    _id: new ObjectId('650000000000000000000104'),
    id: 'post-104',
    user_id: 'user-ray',
    username: 'ray_swing',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    trade_id: 'trade-104',
    symbol: 'GBPUSD',
    market: 'Forex',
    strategy_id: 'swing',
    strategy_name: 'MACRO SWING',
    position_type: 'BUY',
    status: 'OPEN',
    entry_price: 1.29150,
    current_price: 1.29840,
    progress: 88,
    profit: 1380.00,
    profit_percent: 5.34,
    lot: 2.00,
    stop_loss: 1.28600,
    take_profit: 1.30200,
    pips: 69.0,
    duration: 'Live (4j 00m)',
    opened_at: new Date(Date.now() - 240 * 60000),
    closed_at: null,
    visibility: 'LOCKED',
    unlock_price: 1,
    auto_description: 'Terbuka otomatis via cTrader Open API: BUY 2.00 Lot GBPUSD di level 1.29150.',
    custom_description: 'Swing posisi 3 hari ke depan mengikuti data inflasi UK yang kokoh. Support channel Daily terkonfirmasi.',
    likes_count: 96,
    comments_count: 14,
    liked_by_user_ids: [],
    created_at: new Date(Date.now() - 238 * 60000),
    updated_at: new Date(Date.now() - 238 * 60000)
  }
];

export const SEED_COMMENTS: MongoComment[] = [
  {
    _id: new ObjectId(),
    id: 'comm-1',
    post_id: 'post-101',
    user_id: 'user-sarah',
    text: 'Setup breakout yang solid! Ikut follow buy 0.5 lot.',
    created_at: new Date(Date.now() - 25 * 60000),
    updated_at: new Date(Date.now() - 25 * 60000)
  },
  {
    _id: new ObjectId(),
    id: 'comm-2',
    post_id: 'post-101',
    user_id: 'user-elena',
    text: 'Ada FVG di 2920 yang sudah di-fill cantik. Semoga hit TP!',
    created_at: new Date(Date.now() - 15 * 60000),
    updated_at: new Date(Date.now() - 15 * 60000)
  }
];

export const SEED_NOTIFICATIONS: MongoNotification[] = [
  {
    _id: new ObjectId(),
    id: 'notif-1',
    user_id: 'user-alex',
    title: 'Trade Baru Di-Follow!',
    message: 'Trader @budi_investor telah meniru posisi XAUUSD Anda via 1-Click Mirroring.',
    type: 'FOLLOW',
    is_read: false,
    created_at: new Date(Date.now() - 12 * 60000)
  },
  {
    _id: new ObjectId(),
    id: 'notif-2',
    user_id: 'user-alex',
    title: 'Komisi Afiliasi Gen-1 Masuk!',
    message: 'Anda menerima +25 ENERGY (Rp 25.000) dari top-up referral @sarah_scalper.',
    type: 'AFFILIATE_COMMISSION',
    is_read: false,
    created_at: new Date(Date.now() - 45 * 60000)
  }
];
